image:
  repository: ghcr.io/REPLACE_WITH_GITHUB_OWNER/python-xray-argo
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: LoadBalancer
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

env:
  UPLOAD_URL: ""
  PROJECT_URL: ""
  AUTO_ACCESS: "false"
  FILE_PATH: ".cache"
  SUB_PATH: "sub"
  UUID: "20e6e496-cf19-45c8-b883-14f5e11cd9f1"
  NEZHA_SERVER: ""
  NEZHA_PORT: ""
  ARGO_DOMAIN: ""
  ARGO_PORT: "8001"
  CFIP: "cf.877774.xyz"
  CFPORT: "443"
  PUBLIC_HOST: ""
  NAME: "env0-xray"
  S5_PORT: ""
  HY2_PORT: ""
  REALITY_PORT: ""
  SHOW_LOG: "true"

secretEnv:
  NEZHA_KEY: ""
  ARGO_AUTH: ""
  CHAT_ID: ""
  BOT_TOKEN: ""
