{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "python-xray-argo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "python-xray-argo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "python-xray-argo.fullname" $ }}
                port:
                  name: http
{{- end }}
{{- end }}
{{- with .Values.ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
