apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-xray-argo.fullname" . }}-secrets
type: Opaque
stringData:
{{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
