apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-xray-argo.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "python-xray-argo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  app.py: |
{{ .Files.Get "files/app.py" | nindent 4 }}
  requirements.txt: |
{{ .Files.Get "files/requirements.txt" | nindent 4 }}
